version: '3'

services:
  database:
    image: postgres:alpine
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    networks:
      - LVWM.network
  server:
    image: node:alpine
    volumes:
      - ./backend/server:/www
    working_dir: /www
    networks:
      - LVWM.network
  cache:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - LVWM.network
  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/www
    working_dir: /www
    networks:
      - LVWM.network
volumes:
  database-storage:
networks:
  LVWM.network: